export const SliderData = [
    {
        image:
        '/../Images/shoe1.jpg'
    },
    {
        image:
        '/../Images/shoe3.jpg'
    },
    {
        image:
        '/../Images/shoe2.jpg'
    },
    {
        image:
        '/../Images/shoe1.jpg'
    },
    {
        image:
        '/../Images/shoe3.jpg'
    }
];